INSERT INTO missions (name, launch_date, status, description) VALUES
('Apollo 11', '1969-07-16', 'Completed', 'First manned moon landing'),
('Voyager 1', '1977-09-05', 'Ongoing', 'Exploration of outer planets and interstellar space'),
('Curiosity Rover', '2011-11-26', 'Ongoing', 'Mars rover exploring the surface of Mars'),
('Hubble Space Telescope', '1990-04-24', 'Ongoing', 'Orbiting telescope for astronomical observations'),
('ISS Expedition 1', '2000-10-31', 'Completed', 'First long-duration stay aboard the International Space Station'),
('James Webb Space Telescope', '2021-12-25', 'Ongoing', 'Large space-based observatory for astronomical observations'),
('Artemis I', '2022-11-16', 'Completed', 'Uncrewed test flight around the Moon for the Artemis program'),
('Mars 2020 Perseverance', '2020-07-30', 'Ongoing', 'Mars rover mission to seek signs of ancient life and collect samples'),
('Galileo', '1989-10-18', 'Completed', 'Study of Jupiter and its moons'),
('New Horizons', '2006-01-19', 'Ongoing', 'Flyby study of Pluto and the Kuiper Belt'),
('Apollo 13', '1970-04-11', 'Aborted', 'Third crewed mission to land on the Moon, aborted due to an oxygen tank explosion'),
('Pioneer 10', '1972-03-02', 'Completed', 'First spacecraft to travel through the asteroid belt and make a flyby of Jupiter'),
('Cassini-Huygens', '1997-10-15', 'Completed', 'Study of Saturn and its moons, including the Huygens probe landing on Titan'),
('Rosetta', '2004-03-02', 'Completed', 'ESA mission to study comet 67P/Churyumov–Gerasimenko, including the Philae lander'),
('Sputnik 1', '1957-10-04', 'Completed', 'First artificial Earth satellite launched by the Soviet Union'),
('Luna 2', '1959-09-12', 'Completed', 'First spacecraft to reach the Moon'),
('Vostok 1', '1961-04-12', 'Completed', 'First human spaceflight, carried Yuri Gagarin into orbit'),
('Skylab', '1973-05-14', 'Completed', 'First United States space station'),
('Chandra X-ray Observatory', '1999-07-23', 'Ongoing', 'NASA space telescope for X-ray astronomy');
